server:
  port: 8091

spring:
  application:
    name: ruoyi-seata-server
  main:
    web-application-type: none
  profiles:
    # 环境配置
    active: @profiles.active@

logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logs/seata
#  extend:
#    logstash-appender:
#      destination: 127.0.0.1:4560
#    kafka-appender:
#      bootstrap-servers: 127.0.0.1:9092
#      topic: logback_to_logstash

seata:
  config:
    # support: nacos 、 consul 、 apollo 、 zk  、 etcd3
    type: nacos
    nacos:
      server-addr: @nacos.server@
      group: @nacos.discovery.group@
      namespace: ${spring.profiles.active}
      username: @nacos.username@
      password: @nacos.password@
      ##if use MSE Nacos with auth, mutex with username/password attribute
      #access-key: ""
      #secret-key: ""
      data-id: seata-server.properties
  registry:
    # support: nacos 、 eureka 、 redis 、 zk  、 consul 、 etcd3 、 sofa
    type: nacos
    nacos:
      application: ${spring.application.name}
      server-addr: @nacos.server@
      group: @nacos.discovery.group@
      namespace: ${spring.profiles.active}
      cluster: default
      username: @nacos.username@
      password: @nacos.password@
      ##if use MSE Nacos with auth, mutex with username/password attribute
      #access-key: ""
      #secret-key: ""
